SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+05:00";
CREATE DATABASE IF NOT EXISTS `tarabut` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `tarabut`;
CREATE TABLE `preferences` (
`ID` int(11) NOT NULL,
`USER_IDENTIFIER` text NOT NULL,
`SMS` BOOLEAN NOT NULL DEFAULT 0,
`POST` BOOLEAN NOT NULL DEFAULT 0,
`EMAIL` BOOLEAN NOT NULL DEFAULT 0,
`CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE `preferences` ADD PRIMARY KEY (`ID`);
ALTER TABLE `preferences` MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;
