version: "3.9"
services:
  mysql-db:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    volumes:
      - ./.data/sql:/var/lib/mysql
      - ./mysql-tarabut/init.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
  tarabut-retriever:
    build: ./retriever
    ports:
      - "443:443"
    environment:
      spring.datasource.url: "jdbc:mysql://mysql-db:3306/tarabut?useTimezone=true&serverTimezone=UTC"
      spring.datasource.password: "password"
  tarabut-updater:
    build: ./updater
    ports:
      - "8443:443"
    environment:
      spring.datasource.url: "jdbc:mysql://mysql-db:3306/tarabut?useTimezone=true&serverTimezone=UTC"
      spring.datasource.password: "password"
